config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        welcome#index
#           client_invoice_transactions GET    /clients/:client_id/invoices/:invoice_id/transactions(.:format)                          transactions#index
#                                       POST   /clients/:client_id/invoices/:invoice_id/transactions(.:format)                          transactions#create
#        new_client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/new(.:format)                      transactions#new
#       edit_client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/:id/edit(.:format)                 transactions#edit
#            client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#show
#                                       PATCH  /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#update
#                                       PUT    /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#update
#                                       DELETE /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#destroy
#                client_invoice_confirm POST   /clients/:client_id/invoices/:invoice_id/confirm(.:format)                               invoices#confirm
#                 client_invoice_cancel POST   /clients/:client_id/invoices/:invoice_id/cancel(.:format)                                invoices#cancel
#          client_invoice_update_amount POST   /clients/:client_id/invoices/:invoice_id/update_amount(.:format)                         invoices#update_amount
#                       client_invoices GET    /clients/:client_id/invoices(.:format)                                                   invoices#index
#                                       POST   /clients/:client_id/invoices(.:format)                                                   invoices#create
#                    new_client_invoice GET    /clients/:client_id/invoices/new(.:format)                                               invoices#new
#                   edit_client_invoice GET    /clients/:client_id/invoices/:id/edit(.:format)                                          invoices#edit
#                        client_invoice GET    /clients/:client_id/invoices/:id(.:format)                                               invoices#show
#                                       PATCH  /clients/:client_id/invoices/:id(.:format)                                               invoices#update
#                                       PUT    /clients/:client_id/invoices/:id(.:format)                                               invoices#update
#                                       DELETE /clients/:client_id/invoices/:id(.:format)                                               invoices#destroy
#                               clients GET    /clients(.:format)                                                                       clients#index
#                                       POST   /clients(.:format)                                                                       clients#create
#                            new_client GET    /clients/new(.:format)                                                                   clients#new
#                           edit_client GET    /clients/:id/edit(.:format)                                                              clients#edit
#                                client GET    /clients/:id(.:format)                                                                   clients#show
#                                       PATCH  /clients/:id(.:format)                                                                   clients#update
#                                       PUT    /clients/:id(.:format)                                                                   clients#update
#                                       DELETE /clients/:id(.:format)                                                                   clients#destroy
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'clients#index'
  resources :clients do
    resources :invoices do
      resources :transactions
      post 'confirm'
      post 'cancel'
      post 'update_amount'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id             :integer          not null, primary key
#  status         :string
#  payment_status :string
#  amount         :float
#  paid_amount    :float
#  issue_date     :date
#  due_date       :date
#  client_id      :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Invoice < ApplicationRecord
  STATUSES = %w[NEW CONFIRMED CANCELLED].freeze
  PAYMENT_STATUSES = %w[PAID UNPAID UNDERPAID].freeze

  belongs_to :client
  has_many :transactions, dependent: :destroy

  validates :status, presence: true, inclusion: STATUSES
  validates :payment_status, presence: true, inclusion: PAYMENT_STATUSES

  scope :by_client_id, ->(client_id) { where(client_id: client_id) }

  def cancel
    update(status: 'CANCELLED')
  end

  def confirm
    update(status: 'CONFIRMED')
  end

  def update_amount
    update(amount: compute_amount)
  end

  def compute_amount
    if transactions.empty?
      0
    else
      transactions.sum(&:amount)
    end
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy confirm cancel update_amount ]
  before_action :set_client

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.by_client_id(@client.id)
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @form_path = client_invoices_path(@client)
  end

  # GET /invoices/1/edit
  def edit
    @form_path = client_invoice_path(id: @invoice.id)
  end

  def confirm
    @invoice.confirm
    redirect_to client_invoice_url(id: @invoice.id), notice: "Invoice was successfully confirmed."
  end

  def cancel
    @invoice.cancel
    redirect_to client_invoice_url(id: @invoice.id), notice: "Invoice was successfully cancelled."
  end

  def update_amount
    @invoice.update_amount
    redirect_to client_invoice_url(id: @invoice.id), notice: "Invoice amount was successfully updated."
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to client_invoices_url(id: @client.id), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to client_invoices_url(id: @client.id), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to client_invoices_url(id: @client.id), notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id] || params[:invoice_id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:status, :payment_status, :amount, :paid_amount, :issue_date, :due_date, :client_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true, url: @form_path) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :payment_status %>
    <%= form.text_field :payment_status %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.text_field :paid_amount %>
  </div>

  <div class="field">
    <%= form.label :issue_date %>
    <%= form.date_select :issue_date %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field hidden">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, value: @client&.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %> /
  Edit
</h1>

<%= render 'form', invoice: @invoice, client: @client %>

<%= link_to 'Show', client_invoice_path(id: @invoice.id) %> |

app/views/invoices/index.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / 
  <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %>
</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr class='align-left'>
      <th>Status</th>
      <th>Payment status</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th>Issue date</th>
      <th>Due date</th>
      <th>Client</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.status %></td>
        <td><%= invoice.payment_status %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.paid_amount %></td>
        <td><%= invoice.issue_date %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.client_id %></td>
        <td><%= link_to 'Show', client_invoice_path(id: invoice.id) %></td>
        <td><%= link_to 'Transactions', client_invoice_transactions_path(invoice_id: invoice.id) %></td>
        <td><%= link_to 'Edit', edit_client_invoice_path(id: invoice.id) %></td>
        <td><%= link_to 'Confirm', client_invoice_confirm_path(invoice_id: invoice.id), method: :post %></td>
        <td><%= link_to 'Cancel', client_invoice_cancel_path(invoice_id: invoice.id), method: :post %></td>
        <td><%= link_to 'Update Amount', client_invoice_update_amount_path(invoice_id: invoice.id), method: :post %></td>
        <td class='red'><%= link_to 'Destroy', client_invoice_path(id: @client.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_client_invoice_path %>

app/views/invoices/new.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  New
</h1>

<%= render 'form', invoice: @invoice %>

app/views/invoices/show.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %>
</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @invoice.status %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @invoice.payment_status %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @invoice.paid_amount %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @invoice.issue_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @invoice.due_date %>
</p>

<p>
  <strong>Client:</strong>
  <%= @invoice.client_id %>
</p>

<p>
  <strong><%= link_to 'Transactions', client_invoice_transactions_path(invoice_id: @invoice.id) %></strong>
  <strong><%= link_to 'Confirm', client_invoice_confirm_path(invoice_id: @invoice.id), method: :post %></strong>
  <strong><%= link_to 'Cancel', client_invoice_cancel_path(invoice_id: @invoice.id), method: :post %></strong>
  <strong><%= link_to 'Update Amount', client_invoice_update_amount_path(invoice_id: @invoice.id), method: :post %></strong>
</p>

<%= link_to 'Edit', edit_client_invoice_path(@invoice) %>