config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        welcome#index
#           client_invoice_transactions GET    /clients/:client_id/invoices/:invoice_id/transactions(.:format)                          transactions#index
#                                       POST   /clients/:client_id/invoices/:invoice_id/transactions(.:format)                          transactions#create
#        new_client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/new(.:format)                      transactions#new
#       edit_client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/:id/edit(.:format)                 transactions#edit
#            client_invoice_transaction GET    /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#show
#                                       PATCH  /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#update
#                                       PUT    /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#update
#                                       DELETE /clients/:client_id/invoices/:invoice_id/transactions/:id(.:format)                      transactions#destroy
#                client_invoice_confirm POST   /clients/:client_id/invoices/:invoice_id/confirm(.:format)                               invoices#confirm
#                 client_invoice_cancel POST   /clients/:client_id/invoices/:invoice_id/cancel(.:format)                                invoices#cancel
#          client_invoice_update_amount POST   /clients/:client_id/invoices/:invoice_id/update_amount(.:format)                         invoices#update_amount
#                       client_invoices GET    /clients/:client_id/invoices(.:format)                                                   invoices#index
#                                       POST   /clients/:client_id/invoices(.:format)                                                   invoices#create
#                    new_client_invoice GET    /clients/:client_id/invoices/new(.:format)                                               invoices#new
#                   edit_client_invoice GET    /clients/:client_id/invoices/:id/edit(.:format)                                          invoices#edit
#                        client_invoice GET    /clients/:client_id/invoices/:id(.:format)                                               invoices#show
#                                       PATCH  /clients/:client_id/invoices/:id(.:format)                                               invoices#update
#                                       PUT    /clients/:client_id/invoices/:id(.:format)                                               invoices#update
#                                       DELETE /clients/:client_id/invoices/:id(.:format)                                               invoices#destroy
#                               clients GET    /clients(.:format)                                                                       clients#index
#                                       POST   /clients(.:format)                                                                       clients#create
#                            new_client GET    /clients/new(.:format)                                                                   clients#new
#                           edit_client GET    /clients/:id/edit(.:format)                                                              clients#edit
#                                client GET    /clients/:id(.:format)                                                                   clients#show
#                                       PATCH  /clients/:id(.:format)                                                                   clients#update
#                                       PUT    /clients/:id(.:format)                                                                   clients#update
#                                       DELETE /clients/:id(.:format)                                                                   clients#destroy
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'clients#index'
  resources :clients do
    resources :invoices do
      resources :transactions
      post 'confirm'
      post 'cancel'
      post 'update_amount'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :set_client
  before_action :set_invoice

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.by_invoice_id(@invoice.id)
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @form_path = client_invoice_transactions_path(id: @invoice.id)
  end

  # GET /transactions/1/edit
  def edit
    @form_path = client_invoice_transaction_path(id: @transaction.id)
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to client_invoice_transaction_url(id: @transaction.id), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to client_invoice_transaction_url(id: @transaction.id), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to client_invoice_transactions_url(invoice_id: @invoice.id), notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_invoice
      @invoice = Invoice.find(params[:invoice_id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:unit_amount, :quantity, :date, :description, :invoice_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true, url: @form_path) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :unit_amount %>
    <%= form.text_field :unit_amount %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.text_field :invoice_id, value: @invoice.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %> /
  <%= link_to "Transactions", client_invoice_transactions_path(invoice_id: @invoice.id, client_id: @client.id) %> /
  <%= link_to "#{@transaction.id}", client_invoice_transaction_path(id: @transaction.id) %> /
  Edit
</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', client_invoice_transaction_path(id: @transaction.id) %>

app/views/transactions/index.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %> /
  <%= link_to "Transactions", client_invoice_transactions_path(invoice_id: @invoice.id, client_id: @client.id) %> /
</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Unit amount</th>
      <th>Quantity</th>
      <th>Date</th>
      <th>Description</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.unit_amount %></td>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.invoice_id %></td>
        <td><%= link_to 'Show', client_invoice_transaction_path(id: transaction.id) %></td>
        <td><%= link_to 'Edit', edit_client_invoice_transaction_path(id: transaction.id) %></td>
        <td><%= link_to 'Destroy', client_invoice_transaction_path(id: transaction.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_client_invoice_transaction_path %>

app/views/transactions/new.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %> /
  <%= link_to "Transactions", client_invoice_transactions_path(invoice_id: @invoice.id, client_id: @client.id) %> /
  New
</h1>

<%= render 'form', transaction: @transaction %>

app/views/transactions/show.html.erb
<h1>
  <%= link_to 'Clients', clients_path %> / <%= link_to "#{@client.id}", @client %> / 
  <%= link_to "Invoices", client_invoices_path(@client) %> /  
  <%= link_to "#{@invoice.id}", client_invoice_path(id: @invoice.id) %> /
  <%= link_to "Transactions", client_invoice_transactions_path(invoice_id: @invoice.id, client_id: @client.id) %> /
  <%= link_to "#{@transaction.id}", client_invoice_transaction_path(id: @transaction.id) %> /
</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Unit amount:</strong>
  <%= @transaction.unit_amount %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @transaction.invoice_id %>
</p>

<%= link_to 'Edit', edit_client_invoice_transaction_path(id: @transaction.id) %>